######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 12 02:39:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


QT+=sql
QT+=network
# Input
HEADERS += myserver.h mytask.h people.h peoplelist.h privatecouple.h
SOURCES += main.cpp myserver.cpp mytask.cpp people.cpp peoplelist.cpp privatecouple.cpp
