######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 8 11:35:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT+=network

# Input
HEADERS += myserver.h mytask.h
SOURCES += main.cpp myserver.cpp mytask.cpp
